### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by Truemedia** [strarsis/eyeglass-file-text#3]
Hi there,
I'm attempting to use this for the first time on my local sass site instance.

Installed via node and I get this error when attempting to import the lib using `@import 'file-text';`

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'file-text';
^

File to import not found or unreadable: file-text.
```

I'm using webpack and I know it's setup to include from node correctly as Iv'e managed to import other third party libs using import directives in my main sass file. Any ideas?

**Comment by strarsis** [comment]
This may be due to how webpack is loading external node modules.
This project is for eyeglass, a loader independent from webpack 
(in a time where gulp/grunt workflows were common).

For webpack you can inline text files directly in your CSS or SASS, 
either by using a webpack or postCSS plugin, e.g. https://github.com/jantimon/postcss-inline.

You can actually also use this eyeglass plugin, 
but you have to setup eyeglass support in webpack/sass loader, see https://stackoverflow.com/a/43941595/4150808.
